### ISSUE TITLE
Text input is invisible

### ISSUE THREAD

**Issue by MathiasCiarlo** [dhis2msg/DHISmessenger#1]
[This commit](1571c97f76d01eeaba5012a2f1113be51a30d283) introduced a bug where the text in the input box in the IM-module is invisible. Tested on Android 5.0.1. Good luck @hffahle

**Comment by hffahle** [comment]
I fixed the bug with [this](45a6e22c61ad4cd63913ca15b7978d0401c7e3b1) commit.
