### ISSUE TITLE
Refresh does not work

### ISSUE THREAD

**Issue by MathiasCiarlo** [dhis2msg/DHISmessenger#11]

**Comment by livthomas** [comment]
Can you provide some more information? What kind of refresh? Is this related to the REST messaging, XMPP chat or something else?

**Comment by VladislavAlfredov** [comment]
I am guessing that you are refering to InboxFragment.refresh(int page) ?
I just refactored the function to allow you to specify that you would like to skip the cache.

**Comment by MathiasCiarlo** [comment]
Yes, sorry about that, it was supposed to be a description below! Vladislav is correct, refresh does not show new conversations, nor new messages in the inbox.
