### ISSUE TITLE
Update DHIS2 API calls

### ISSUE THREAD

**Issue by MathiasCiarlo** [dhis2msg/DHISmessenger#3]
The current ones do not work with the current API.

**Comment by livthomas** [comment]
I think this is more of a bug since the application cannot run at all with the latest version of DHIS server and it also prevents us from testing the application easily.

**Comment by MathiasCiarlo** [comment]
I was thinking the same when I posted it. However I decided it was not a bug since it is a compatibility issue introduced after the app was finished. For example: If you are a sausage factory and produced a sausage which was compatible (by size) with, let's say IKEA's frying pans, and later discover (some years later) that they changed the size on their pans. You wouldn't call that a bug, would you? ;)

**Comment by MathiasCiarlo** [comment]
Now it's both a bug and an enhancement :)

**Comment by MathiasCiarlo** [comment]
The API calls need no update, how ever, the author wants us to use RxAndroid for the rest calls
