### ISSUE TITLE
Interpretations cause an exception (local DHIS2 server)

### ISSUE THREAD

**Issue by VladislavAlfredov** [dhis2msg/DHISmessenger#6]
(When using a local DHIS2 server ie the newer version of DHIS2.)

When you click on Interpretations the app stops with the message "Unfortunately org.dhis2.messaging has stopped working".
This is caused by an uncaught exception in RESTGetInterpretation.
Probably due to changes to do with the REST client's api / json specifications.

The exception is:
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime: FATAL EXCEPTION: main
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime: Process: org.dhis2.messaging, PID: 24964
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at java.util.ArrayList.get(ArrayList.java:308)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at org.dhis2.messaging.Fragments.InterpretationsFragment.updateList(InterpretationsFragment.java:69)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at org.dhis2.messaging.Utils.AsyncroniousTasks.RESTGetInterpretation.onPostExecute(RESTGetInterpretation.java:136)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at org.dhis2.messaging.Utils.AsyncroniousTasks.RESTGetInterpretation.onPostExecute(RESTGetInterpretation.java:32)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.os.AsyncTask.finish(AsyncTask.java:636)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.os.AsyncTask.access$500(AsyncTask.java:177)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:211)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5389)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
11-26 15:54:47.231 24964-24964/org.dhis2.messaging E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by MathiasCiarlo** [comment]
It somehow works on the play server, but not on our local ones... Testing more

**Comment by VladislavAlfredov** [comment]
Commits: 30dd9c29e77b2ef2e50ad571eb0064864611a70a and b61ff05938d6141c3d0754cd192e8c45f8e992d3, by jiaderc solve this issue.
